### ISSUE TITLE
/opt/vc/bin/vcgencmd no such file

### ISSUE THREAD

**Issue by victor7376** [pageauc/speed-camera#141]
Hi m8,  Not sure if this is a bug or not but after I quit out of menu.sh I now see an error saying:

./menubox.sh: line 727: /opt/vc/bin/vcgencmd: No such file or directory

**Comment by pageauc** [comment]
OK Thanks.  Updated.  I guess it moved.  Since it is on the PATH, the full path would not really be required.  In this case I changed to /usr/bin/vcgencmd.

Thanks for your help ...
