### ISSUE TITLE
Docker Install always 11.22

### ISSUE THREAD

**Issue by SpaceRichard** [pageauc/speed-camera#155]
Hi :)

it's an really an interesting project, however I have some trouble to install it.
System: Mac with Docker

If I follow the instruction it always install 11.22 instead of 13.16 or never.
I already try to adapt the Dockerfile, as there I found the reference to 11.22.

Is there a trick i missed?
Thanks

**Comment by jeremyward** [comment]
I see this too.  It looks like the docker-compose up is pulling the container from randallkent on docker hub (https://hub.docker.com/r/randallkent/speed-camera).  And that thing hasn't been updated in 2 years.  I was able to build and run the 13.2 version in a docker container.  But I haven't see a lot of benefits of the newer version yet.
