### ISSUE TITLE
Duplicate File Error and SQL Error

### ISSUE THREAD

**Issue by BigDuke6nc** [pageauc/speed-camera#32]
Application is crashing when there is a duplicate track at the same time. Unable to write the record in the database and to the file system. Log link below.

[https://pastebin.com/33hWPpQd](https://pastebin.com/33hWPpQd)

**Comment by BigDuke6nc** [comment]
No worries. I thought I had changed those values as well but when I looked they were default with the deployment. I can probably tweak those values.

**Comment by pageauc** [comment]
I have added tenth of second to file naming.  I think this should be good enough but it could be easily changed to hundredths if needed.  This should not happen with normal reset times but this should solve your problem and not make naming too long.

I have tested bu Let me know result
Claude ...

**Comment by BigDuke6nc** [comment]
Seems to have fixed the issue.
