### ISSUE TITLE
Feature request: Support for RTSP IP cameras

### ISSUE THREAD

**Issue by rafik24** [pageauc/speed-camera#34]
Hi Claude,

Thank you for this great project.

I was wondering if you are planning to enhance the inputs to support RTSP IP cameras ?

Merci,
Rafik

**Comment by pageauc** [comment]
I don not use ip cameras to not able to test.  Here is an article regarding how to use opencv to capture ip camera images.  Not sure if if works but if you try this and it works then let me know.  

https://stackoverflow.com/questions/49978705/access-ip-camera-in-python-opencv

**Comment by rafik24** [comment]
Thanks Claude,
I will give it a try and come back to you.
Rafik
    On Monday, 20 May 2019, 13:44:36 BST, Claude Pageau <notifications@github.com> wrote:  
 
 
I don not use ip cameras to not able to test. Here is an article regarding how to use opencv to capture ip camera images. Not sure if if works but if you try this and it works then let me know.

https://stackoverflow.com/questions/49978705/access-ip-camera-in-python-opencv

**Comment by pageauc** [comment]
If you need help I can do some of the coding but you will have to test.
Regards Claude ...

**Comment by pageauc** [comment]
You might try setting up speed camera for webcam  in config.py  

    WEBCAM = False

    WEBCAM_SRC = '"tsp://cam_ip:cam_port/1"
or
    WEBCAM_SRC = "rtsp://user:passwd@cam_ip:cam_port/1"

You will need to substitute user, passwdm cam_ip and cam_port to match your IP camera
Give this a try to see if you get errors.

Then try to run to see if it works.
