### ISSUE TITLE
motion crop area in plugins

### ISSUE THREAD

**Issue by mf76130** [pageauc/speed-camera#85]
Hi,

Nice work, thanks a lot for that very nice project!

In case you are looking to improve it, i would find the option to have the crop area in the camera plugins.
Or can i just add them and then they are overwritting these settings?

br
Michael

**Comment by pageauc** [comment]
The following settings override the auto calculated crop area 
Uncomment the variables to override

Note: To see motion tracking crop area on images, Set variable image_show_motion_area = True

# Allow user to customize the motion crop area (width) x values
# If variables not found then values will be set automatically base on image size.
# x_left = 50          # uncomment and change values to override auto calculate
# x_right = 300        # uncomment and change values to override auto calculate

# Allow user to customize the motion crop area (height) y values
# If variables not found then values will be set automatically base on image size.
# y_upper = 80         # uncomment and change values to override auto calculate
# y_lower = 180        # uncomment and change values to override auto calculate

Also I have written new graphing using matplot lib in latest update.  See the sql-make-graph...py files. After the upgrade you will need to copy the config.py.new to config.py to see the new variables.

![graph_count_prev28days_byday_ge0kph](https://user-images.githubusercontent.com/5961060/119871165-ccf0fb80-bee7-11eb-9d0c-61be96a69a7e.jpg)
![graph_speed_prev2days_byhour_ge0kph](https://user-images.githubusercontent.com/5961060/119871167-ccf0fb80-bee7-11eb-9221-0d68eec505e4.jpg)
